### ISSUE TITLE
Progress bar doesn't work inside a loop

### ISSUE THREAD

**Issue by Sidd27** [jhuckaby/pixl-cli#3]
Hi,

I think as you are using setInterval to update the progress bar the progress bar is not getting update on main queue of javascript if you change the logic to normally update on user input the user can decide whether he want the data to be update on interval or in normal flow of execution

as Interval and timeout goes to poll queue

```
var total = 1000000;

cli.progress.start({
  max: total
});

for (let index = 0; index < total; index++) {
  cli.progress.update(index);
}

cli.progress.end();
```

**Comment by jhuckaby** [comment]
Yup, you are correct, the spinner updater is designed for asynchronous tasks, where the Node.js event loop has a chance to fire its own timers.  If the event loop is totally hung up and CPU-bound doing a single task, then the timers do not fire, and I cannot update the spinner.

However, if you want, you can just call the draw routine in your own loop, and it forces an immediate draw:

```js
cli.progress.draw();
```

However, I would advise caution.  You wouldn't want to call the draw function on EVERY iteration in a fast loop like your example.  Maybe more like every 1000th iteration, depending on how fast it is.

```js
for (let index = 0; index < total; index++) {
  cli.progress.update(index);
  if (index % 1000 == 0) cli.progress.draw();
}
```
